version: "3.8"
services:
  beershop:
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      ADDR: ":8080"
      DB_USER: "postgres"
      DB_PASSWORD: "supersecret"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_RETRIES: 5
      DB_TIMEOUT: 2000

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - ../../db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
