version: "3.8"
services:
  beershop:
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"

  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - ../../db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
