// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: beershop.proto

package grpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the Beer details
type CreateBeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Abv  float32 `protobuf:"fixed32,2,opt,name=Abv,proto3" json:"Abv,omitempty"`
}

func (x *CreateBeerRequest) Reset() {
	*x = CreateBeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerRequest) ProtoMessage() {}

func (x *CreateBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerRequest.ProtoReflect.Descriptor instead.
func (*CreateBeerRequest) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBeerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBeerRequest) GetAbv() float32 {
	if x != nil {
		return x.Abv
	}
	return 0
}

// The response message containing the id of the Beer
type CreateBeerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *CreateBeerReply) Reset() {
	*x = CreateBeerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBeerReply) ProtoMessage() {}

func (x *CreateBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBeerReply.ProtoReflect.Descriptor instead.
func (*CreateBeerReply) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBeerReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// The request message for the read request
type ReadBeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *ReadBeerRequest) Reset() {
	*x = ReadBeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBeerRequest) ProtoMessage() {}

func (x *ReadBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBeerRequest.ProtoReflect.Descriptor instead.
func (*ReadBeerRequest) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBeerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// The response message to the read request
type ReadBeerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beer *Beer `protobuf:"bytes,1,opt,name=Beer,proto3" json:"Beer,omitempty"`
}

func (x *ReadBeerReply) Reset() {
	*x = ReadBeerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBeerReply) ProtoMessage() {}

func (x *ReadBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBeerReply.ProtoReflect.Descriptor instead.
func (*ReadBeerReply) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBeerReply) GetBeer() *Beer {
	if x != nil {
		return x.Beer
	}
	return nil
}

// The request message for the delete request
type DeleteBeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeleteBeerRequest) Reset() {
	*x = DeleteBeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerRequest) ProtoMessage() {}

func (x *DeleteBeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerRequest.ProtoReflect.Descriptor instead.
func (*DeleteBeerRequest) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBeerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// The response message to the delete request
type DeleteBeerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBeerReply) Reset() {
	*x = DeleteBeerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBeerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBeerReply) ProtoMessage() {}

func (x *DeleteBeerReply) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBeerReply.ProtoReflect.Descriptor instead.
func (*DeleteBeerReply) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{5}
}

// The request message for the list activities request
type ListActivitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterIds []string `protobuf:"bytes,1,rep,name=FilterIds,proto3" json:"FilterIds,omitempty"`
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{6}
}

func (x *ListActivitiesRequest) GetFilterIds() []string {
	if x != nil {
		return x.FilterIds
	}
	return nil
}

// The response message to the list activities request.
type ListActivitiesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beers []*Beer `protobuf:"bytes,1,rep,name=Beers,proto3" json:"Beers,omitempty"`
}

func (x *ListActivitiesReply) Reset() {
	*x = ListActivitiesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActivitiesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesReply) ProtoMessage() {}

func (x *ListActivitiesReply) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesReply.ProtoReflect.Descriptor instead.
func (*ListActivitiesReply) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{7}
}

func (x *ListActivitiesReply) GetBeers() []*Beer {
	if x != nil {
		return x.Beers
	}
	return nil
}

type Beer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string  `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string  `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Abv  float32 `protobuf:"fixed32,3,opt,name=Abv,proto3" json:"Abv,omitempty"`
}

func (x *Beer) Reset() {
	*x = Beer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beershop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beer) ProtoMessage() {}

func (x *Beer) ProtoReflect() protoreflect.Message {
	mi := &file_beershop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beer.ProtoReflect.Descriptor instead.
func (*Beer) Descriptor() ([]byte, []int) {
	return file_beershop_proto_rawDescGZIP(), []int{8}
}

func (x *Beer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beer) GetAbv() float32 {
	if x != nil {
		return x.Abv
	}
	return 0
}

var File_beershop_proto protoreflect.FileDescriptor

var file_beershop_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x65, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x39, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x41, 0x62, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x41, 0x62,
	0x76, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x42, 0x65, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x42,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x65,
	0x65, 0x72, 0x52, 0x04, 0x42, 0x65, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x11, 0x0a,
	0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x35, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x37, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20,
	0x0a, 0x05, 0x42, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x42, 0x65, 0x65, 0x72, 0x52, 0x05, 0x42, 0x65, 0x65, 0x72, 0x73,
	0x22, 0x3c, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x62, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x41, 0x62, 0x76, 0x32, 0xfa,
	0x01, 0x0a, 0x08, 0x42, 0x65, 0x65, 0x72, 0x73, 0x68, 0x6f, 0x70, 0x12, 0x3a, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x65, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x48, 0x03, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x46, 0x72, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x63, 0x6f, 0x49, 0x6c, 0x61, 0x72, 0x69, 0x6f, 0x2f, 0x42, 0x65, 0x65, 0x72,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beershop_proto_rawDescOnce sync.Once
	file_beershop_proto_rawDescData = file_beershop_proto_rawDesc
)

func file_beershop_proto_rawDescGZIP() []byte {
	file_beershop_proto_rawDescOnce.Do(func() {
		file_beershop_proto_rawDescData = protoimpl.X.CompressGZIP(file_beershop_proto_rawDescData)
	})
	return file_beershop_proto_rawDescData
}

var file_beershop_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_beershop_proto_goTypes = []interface{}{
	(*CreateBeerRequest)(nil),     // 0: grpc.CreateBeerRequest
	(*CreateBeerReply)(nil),       // 1: grpc.CreateBeerReply
	(*ReadBeerRequest)(nil),       // 2: grpc.ReadBeerRequest
	(*ReadBeerReply)(nil),         // 3: grpc.ReadBeerReply
	(*DeleteBeerRequest)(nil),     // 4: grpc.DeleteBeerRequest
	(*DeleteBeerReply)(nil),       // 5: grpc.DeleteBeerReply
	(*ListActivitiesRequest)(nil), // 6: grpc.ListActivitiesRequest
	(*ListActivitiesReply)(nil),   // 7: grpc.ListActivitiesReply
	(*Beer)(nil),                  // 8: grpc.Beer
}
var file_beershop_proto_depIdxs = []int32{
	8, // 0: grpc.ReadBeerReply.Beer:type_name -> grpc.Beer
	8, // 1: grpc.ListActivitiesReply.Beers:type_name -> grpc.Beer
	0, // 2: grpc.Beershop.Create:input_type -> grpc.CreateBeerRequest
	2, // 3: grpc.Beershop.Read:input_type -> grpc.ReadBeerRequest
	4, // 4: grpc.Beershop.Delete:input_type -> grpc.DeleteBeerRequest
	6, // 5: grpc.Beershop.List:input_type -> grpc.ListActivitiesRequest
	1, // 6: grpc.Beershop.Create:output_type -> grpc.CreateBeerReply
	3, // 7: grpc.Beershop.Read:output_type -> grpc.ReadBeerReply
	5, // 8: grpc.Beershop.Delete:output_type -> grpc.DeleteBeerReply
	7, // 9: grpc.Beershop.List:output_type -> grpc.ListActivitiesReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_beershop_proto_init() }
func file_beershop_proto_init() {
	if File_beershop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beershop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBeerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBeerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBeerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActivitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActivitiesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beershop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beershop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beershop_proto_goTypes,
		DependencyIndexes: file_beershop_proto_depIdxs,
		MessageInfos:      file_beershop_proto_msgTypes,
	}.Build()
	File_beershop_proto = out.File
	file_beershop_proto_rawDesc = nil
	file_beershop_proto_goTypes = nil
	file_beershop_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BeershopClient is the client API for Beershop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeershopClient interface {
	// Creates a new Beer
	Create(ctx context.Context, in *CreateBeerRequest, opts ...grpc.CallOption) (*CreateBeerReply, error)
	// Reads an Beer
	Read(ctx context.Context, in *ReadBeerRequest, opts ...grpc.CallOption) (*ReadBeerReply, error)
	// Delete an Beer
	Delete(ctx context.Context, in *DeleteBeerRequest, opts ...grpc.CallOption) (*DeleteBeerReply, error)
	// List an Beer
	List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error)
}

type beershopClient struct {
	cc grpc.ClientConnInterface
}

func NewBeershopClient(cc grpc.ClientConnInterface) BeershopClient {
	return &beershopClient{cc}
}

func (c *beershopClient) Create(ctx context.Context, in *CreateBeerRequest, opts ...grpc.CallOption) (*CreateBeerReply, error) {
	out := new(CreateBeerReply)
	err := c.cc.Invoke(ctx, "/grpc.Beershop/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beershopClient) Read(ctx context.Context, in *ReadBeerRequest, opts ...grpc.CallOption) (*ReadBeerReply, error) {
	out := new(ReadBeerReply)
	err := c.cc.Invoke(ctx, "/grpc.Beershop/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beershopClient) Delete(ctx context.Context, in *DeleteBeerRequest, opts ...grpc.CallOption) (*DeleteBeerReply, error) {
	out := new(DeleteBeerReply)
	err := c.cc.Invoke(ctx, "/grpc.Beershop/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beershopClient) List(ctx context.Context, in *ListActivitiesRequest, opts ...grpc.CallOption) (*ListActivitiesReply, error) {
	out := new(ListActivitiesReply)
	err := c.cc.Invoke(ctx, "/grpc.Beershop/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeershopServer is the server API for Beershop service.
type BeershopServer interface {
	// Creates a new Beer
	Create(context.Context, *CreateBeerRequest) (*CreateBeerReply, error)
	// Reads an Beer
	Read(context.Context, *ReadBeerRequest) (*ReadBeerReply, error)
	// Delete an Beer
	Delete(context.Context, *DeleteBeerRequest) (*DeleteBeerReply, error)
	// List an Beer
	List(context.Context, *ListActivitiesRequest) (*ListActivitiesReply, error)
}

// UnimplementedBeershopServer can be embedded to have forward compatible implementations.
type UnimplementedBeershopServer struct {
}

func (*UnimplementedBeershopServer) Create(context.Context, *CreateBeerRequest) (*CreateBeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBeershopServer) Read(context.Context, *ReadBeerRequest) (*ReadBeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedBeershopServer) Delete(context.Context, *DeleteBeerRequest) (*DeleteBeerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedBeershopServer) List(context.Context, *ListActivitiesRequest) (*ListActivitiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterBeershopServer(s *grpc.Server, srv BeershopServer) {
	s.RegisterService(&_Beershop_serviceDesc, srv)
}

func _Beershop_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeershopServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beershop/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeershopServer).Create(ctx, req.(*CreateBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beershop_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeershopServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beershop/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeershopServer).Read(ctx, req.(*ReadBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beershop_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeershopServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beershop/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeershopServer).Delete(ctx, req.(*DeleteBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Beershop_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeershopServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Beershop/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeershopServer).List(ctx, req.(*ListActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Beershop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Beershop",
	HandlerType: (*BeershopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Beershop_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Beershop_Read_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Beershop_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Beershop_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beershop.proto",
}
